
STRIPE_LIVE_SECRET_KEY: sk_live_j9quwn1PXM4WxDV7xaB0XtP4
STRIPE_LIVE_PUBLISHABLE_KEY: pk_live_9tY9ifWtHoNndeZFbsoIGmnH

test:
STRIPE_TEST_SECRET_KEY: sk_test_uBT01xTGpB0GGCHcN76rT67i
STRIPE_TEST_PUBLISHABLE_KEY: pk_test_WaF0gM9xOhnq2ZSY8r2aAFAt

development:
STRIPE_TEST_SECRET_KEY: sk_test_uBT01xTGpB0GGCHcN76rT67i
STRIPE_TEST_PUBLISHABLE_KEY: pk_test_WaF0gM9xOhnq2ZSY8r2aAFAt
